// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rviatcrkeeelewxcmspv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2aWF0Y3JrZWVlbGV3eGNtc3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5ODE5NjMsImV4cCI6MjA1MzU1Nzk2M30.54UC8USGTuwCw4Sxlu2b_SFA-10SEIb_vyzXBcAnQ4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
